<?php
$wangzhi = "http://www.360kan.com/dongman/list.php?cat=all&year=all&area=all&act=all&rank=all&pageno=1";
$fcon = file_get_contents($wangzhi);
$vname = '#<span class="s1">(.*?)</span>#';
$fname = '#<span class="s2">(.*?)</span>#';
$vlist = '#<a class="js-tongjic" href="(.*?)">#';
$vstar = '# <p class="star">(.*?)</p>#';
$vvlist = '#<div class="s-tab-main">[\s\S]+?<div class="s-common-body">#';
$vimg = '#<img src="(.*?)">#';
$bflist = '#<a data-daochu(.*?) href="(.*?)" class="js-site-btn btn btn-play"></a>#';
$jishu = '#<span class="hint">(.*?)</span>#';
$fufei = '#<span class="pay">(.*?)</span>#';
$yuming = 'https://www.360kan.com';
preg_match_all($vname, $fcon, $xarr);
preg_match_all($fname, $fcon, $xarrf);
preg_match_all($vlist, $fcon, $xarr1);
preg_match_all($vstar, $fcon, $xarr2);
preg_match_all($vvlist, $fcon, $imglist);
$zcf = implode($glue, $imglist[0]);
preg_match_all($vimg, $zcf, $xarr3);
preg_match_all($bflist, $fcon, $xarr4);
preg_match_all($jishu, $fcon, $xarr5);
preg_match_all($fufei, $fcon, $xarrff);
$xname = $xarr[1];
$lname = $xarrf[1];
$xlist = $xarr1[1];
$xstar = $xarr2[1];
$ximg = $xarr3[1];
$xbflist = $xarr4[1];
$xjishu = $xarr5[1];
$xfufei = $xarrff[1];
echo $xfufei;
